### ISSUE TITLE
decoding of name crashes with non-ascii characters

### ISSUE THREAD

**Issue by phoeft670** [cn-uofbasel/PiCN#27]
def components_to_string in Name.py uses decode(ascii).
Decoding non-ascii chars leads to a UnicodeDecodeError which isn't caught.

**Comment by cmarxer** [comment]
Note: PiCN.Packets.Name.py, line 39

**Comment by cmarxer** [comment]
fixed in 891cdbc8e029aaf44e2d2efd8ed15227fbcacf70
